# Import libraries

In [1]:
import pandas as pd
import numpy as np

# Read the dataset

In [2]:
df = pd.read_csv("historic_with_nulls.csv", sep=",")
df

,record_date,avg_temp,hi_temp,low_temp,out_hum,dew_pt,wind_speed,wind_direction,wind_run,hi_speed,...,in_hum,in_dew,in_heat,in_emc,in_air_density,et,wind_samp,wind_tx,iss_recept,arc_int
0,2008-01-08 14:14:00,32.7,32.7,32.7,24.0,9.5,4.8,SE,0.08,6.4,...,40.0,NaN,NaN,NaN,NaN,0.00,8,1,34.8,1
1,2008-01-08 14:15:00,32.8,32.8,32.7,24.0,9.6,4.8,S,0.08,8.0,...,41.0,13.9,28.0,7.69,1.1484,0.00,24,1,100.0,1
2,2008-01-08 14:16:00,32.8,32.8,32.8,23.0,9.0,8.0,ESE,0.13,12.9,...,40.0,13.6,28.0,7.55,1.1482,0.00,23,1,100.0,1
3,2008-01-08 14:17:00,32.8,32.8,32.8,23.0,9.0,3.2,ESE,0.05,8.0,...,40.0,13.6,28.0,7.55,1.1482,0.00,23,1,100.0,1
4,2008-01-08 14:18:00,32.8,32.8,32.8,23.0,8.9,1.6,NE,0.03,3.2,...,40.0,13.6,28.0,7.55,1.1482,0.00,24,1,100.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645922,2026-05-18 18:45:00,15.6,16.7,15.6,18.0,-8.7,1.6,SSW,0.40,6.4,...,28.0,-0.7,16.0,5.96,1.2076,0.00,352,1,100.0,15
645923,2026-05-18 19:00:00,14.8,15.6,14.8,19.0,-8.6,1.6,SW,0.40,4.8,...,28.0,-0.7,15.9,5.96,1.2079,0.05,348,1,100.0,15
645924,2026-05-18 19:15:00,13.9,14.8,13.9,20.0,-8.7,0.0,SW,0.00,1.6,...,27.0,-1.3,15.7,5.85,1.2090,0.00,351,1,100.0,15
645925,2026-05-18 19:30:00,13.1,13.9,13.1,20.0,-9.4,0.0,SW,0.00,1.6,...,27.0,-1.4,15.6,5.85,1.2097,0.00,351,1,100.0,15
645926,2026-05-18 19:45:00,12.6,13.1,12.6,21.0,-9.2,1.6,SW,0.40,4.8,...,27.0,-1.6,15.4,5.85,1.2106,0.00,352,1,100.0,15

# Comprehending the data

In [3]:
df.describe()

,avg_temp,hi_temp,low_temp,out_hum,dew_pt,wind_speed,wind_run,hi_speed,wind_chill,heat_index,...,in_hum,in_dew,in_heat,in_emc,in_air_density,et,wind_samp,wind_tx,iss_recept,arc_int
count,645750.000000,645753.000000,645753.000000,645749.000000,645748.000000,645927.000000,645927.000000,645927.000000,645750.000000,645748.000000,...,645923.000000,645920.000000,645920.000000,645920.000000,645920.000000,645927.000000,645927.000000,645927.000000,645927.000000,645927.000000
mean,15.587208,15.806107,15.368743,59.559906,6.358955,2.344887,0.581442,7.237907,15.544056,14.988756,...,43.509296,6.757989,18.861953,8.330716,1.194936,0.040644,347.359284,1.000207,99.678010,14.909022
std,8.471183,8.503689,8.436817,21.711808,4.257603,4.136494,1.029683,9.343341,8.451778,8.131828,...,8.509608,3.433078,4.929784,1.442473,0.027045,0.128632,29.119704,0.015737,3.899085,1.093916
min,-4.400000,-4.300000,-4.500000,1.000000,-31.600000,0.000000,0.000000,0.000000,-4.400000,-4.700000,...,16.000000,-11.600000,5.600000,3.780000,1.088100,0.000000,0.000000,1.000000,0.000000,1.000000
25%,9.200000,9.300000,9.000000,41.000000,3.700000,0.000000,0.000000,0.000000,9.100000,9.000000,...,37.000000,4.300000,14.700000,7.280000,1.173000,0.000000,351.000000,1.000000,100.000000,15.000000
50%,14.400000,14.700000,14.200000,61.000000,6.700000,0.000000,0.000000,3.200000,14.400000,13.700000,...,42.000000,6.700000,18.800000,8.140000,1.194200,0.000000,351.000000,1.000000,100.000000,15.000000
75%,21.900000,22.200000,21.700000,79.000000,9.300000,3.200000,0.800000,11.300000,21.900000,21.000000,...,49.000000,9.200000,23.300000,9.210000,1.216000,0.000000,351.000000,1.000000,100.000000,15.000000
max,39.700000,39.800000,39.500000,100.000000,17.900000,25.700000,6.440000,62.800000,39.700000,38.100000,...,78.000000,17.400000,33.800000,15.710000,6.550000,0.940000,586.000000,3.000000,100.000000,15.000000

In [4]:
df.columns

Index(['record_date', 'avg_temp', 'hi_temp', 'low_temp', 'out_hum', 'dew_pt',
       'wind_speed', 'wind_direction', 'wind_run', 'hi_speed', 'hi_dir',
       'wind_chill', 'heat_index', 'thw_index', 'thsw_index', 'bar', 'rain',
       'rain_rate', 'solar_rad', 'solar_energy', 'hi_solar_rad', 'uv_index',
       'uv_dose', 'hi_uv', 'heat_dd', 'cool_dd', 'in_temp', 'in_hum', 'in_dew',
       'in_heat', 'in_emc', 'in_air_density', 'et', 'wind_samp', 'wind_tx',
       'iss_recept', 'arc_int'],
      dtype='str')

This next block describes each of the columns previously obtain on the code block (backed up by the Weatherlink documentation available on the Windows program):
* **record_date:** Date of the archive. Follows a "DD-MM-YY HH:MM:SS" format. The measurement started in January 8, 2008 at 14:14:00.
* **avg_temp:** Average temperature measured during the interval. Reported in Celsius (°C).
* **hi_temp:** Highest temperature measured during the interval. Reported in Celsius (°C).
* **low_temp:** Lowest temperature measured during the interval. Reported in Celsius (°C).
* **out_hum:** Relative humidity. This is the relation between the amount of water vapor present in the air and the maximum amount of water vapor the air can contain at a specific temperature, expressed in percentage (%).
* **dew_pt:** Temperature the air needs to be cooled to in order to produce a relative humidity of 100%. Reported in Celsius (°C).
* **wind_speed:** Average wind speed reading from the station for the interval. Reported in km/h.
* **wind_direction:** Wind Direction. Composed of 16 "bins" representing the 16 compass points, the dominant wind direction (and therefore, the one reported) will be the one that has the most "markers" registered during the time of archive. Usually, it can take the value `---` if there is no wind speed, but can also indicate **bad or missing data.**
* **wind_run:** "Amount" of wind passing the station during a given period of time. Calculated by multiplying Avg. Wind Speed for each archive record by the archive interval. Reported in kilometers.
* **hi_speed:** Highest wind speed value recorded during the interval. Reported in km/h.
* **hi_dir:** Wind Direction of the highest wind speed value recorded.
* **wind_chill:** Perception of air temperature, taking into account the speed of the wind. Calculated with the Osczevski (1995) equation and reported in Celsius (°C)
* **heat_index:** Also known as *apparent temperature*, is how temperature feels like to the human body when relative humidity is combined with the air temperature. Reported in Celsius (°C).
* **thw_index:** Includes the effects of the wind into the Heat Index. Reported in Celsius (°C).
* **thsw_index:** Includes the effects of solar radiation into the THW Index. Reported in Celsius (°C).
* **bar:** Air pressure. Reported in mbar (1 mbar is equivalent to 1 hPa).
* **rain:** Amount of rain that has fallen during the archive interval. Reported in millimeters (mm).
* **rain_rate:** Amount of rain that would fall over a time period. Reported in mm/hr.
* **solar_rad:** Intensity of the sun's radiation reaching a horizontal surface. The value, reported in Watts per square meter (W/m2), is the average solar radiation measured over the archive interval.
* **solar_energy:** Amount of accumulated solar radiation energy over a period of time. Reported in Langleys (L); 1 langley is equivalent to 41840 joules per square metre (J/m2).
* **hi_solar_rad:** Peak solar radiation measured during the archive interval.
* **uv_index:** Intensity of UV, using a scale of 0 to 16. The value logged by WeatherLink is the average UV measured during the archive interval.
* **uv_dose:**
* **hi_uv:** Peak UV measured during the archive interval.
* **heat_dd:**
* **cool_dd:**
* **in_temp:** Average temperature on the room or space where the sensor is located.
* **in_hum:** Average relative humidity on the room or space where the sensor is located.
* **in_dew:** Average dew point on the room or space where the sensor is located.
* **in_heat:**
* **in_emc:** Equilibrium Moisture Content.
* **in_air_density:**
* **et:**
* **wind_samp:** Number of received packets.
* **wind_tx:**
* **iss_recept:** Overall quality level of the radio reception between the Vantage Pro consoles and the ISS transmitter. Reported as a percentage, is calculated from the number of wind speed samples received (Wind Samp) divided by the expected number of packets.
* **arc_int:** Archive Interval, reported in minutes. Starting January 18, 2008, the archive interval has mantained a value of 15 (minutes). Previously, the archive intervals values were 10 (from Jan 11th to Jan 18th, 2008) and 1 (from Jan 8th to Jan 11th, 2008).

# Data Cleaning

## Duplicates

In [5]:
df.duplicated().sum()

np.int64(0)

## Nulls

In [6]:
display(df.isnull().sum())

record_date            0
avg_temp             177
hi_temp              174
low_temp             174
out_hum              178
dew_pt               179
wind_speed             0
wind_direction    225594
wind_run               0
hi_speed               0
hi_dir            225427
wind_chill           177
heat_index           179
thw_index            179
thsw_index         98572
bar                    5
rain                   0
rain_rate              0
solar_rad            176
solar_energy         176
hi_solar_rad         177
uv_index          102075
uv_dose           102075
hi_uv             102078
heat_dd              177
cool_dd              177
in_temp                7
in_hum                 4
in_dew                 7
in_heat                7
in_emc                 7
in_air_density         7
et                     0
wind_samp              0
wind_tx                0
iss_recept             0
arc_int                0
dtype: int64

In [7]:
print(f"Total null amount: {df.isnull().sum().sum()}")

Total null amount: 858165

In [8]:
for column in df:
    if df[column].isnull().sum()/df[column].notnull().sum() != 0:  
        print(f"{column}: {df[column].isnull().sum()/df[column].notnull().sum():.5f} ({df[column].isnull().sum()})")

avg_temp: 0.00027 (177)
hi_temp: 0.00027 (174)
low_temp: 0.00027 (174)
out_hum: 0.00028 (178)
dew_pt: 0.00028 (179)
wind_direction: 0.53670 (225594)
hi_dir: 0.53609 (225427)
wind_chill: 0.00027 (177)
heat_index: 0.00028 (179)
thw_index: 0.00028 (179)
thsw_index: 0.18009 (98572)
bar: 0.00001 (5)
solar_rad: 0.00027 (176)
solar_energy: 0.00027 (176)
hi_solar_rad: 0.00027 (177)
uv_index: 0.18769 (102075)
uv_dose: 0.18769 (102075)
hi_uv: 0.18770 (102078)
heat_dd: 0.00027 (177)
cool_dd: 0.00027 (177)
in_temp: 0.00001 (7)
in_hum: 0.00001 (4)
in_dew: 0.00001 (7)
in_heat: 0.00001 (7)
in_emc: 0.00001 (7)
in_air_density: 0.00001 (7)

Wind Direction and High Direction are the two columns with the most amount of null values. This makes sense since the Weatherlink program treats the no wind periods as "bad data" (null).

In [9]:
df[(df["wind_direction"].isna()) | (df["hi_dir"].isna())]

,record_date,avg_temp,hi_temp,low_temp,out_hum,dew_pt,wind_speed,wind_direction,wind_run,hi_speed,...,in_hum,in_dew,in_heat,in_emc,in_air_density,et,wind_samp,wind_tx,iss_recept,arc_int
418,2008-01-08 21:12:00,24.9,24.9,24.9,43.0,11.5,0.0,NaN,0.0,0.0,...,40.0,13.0,27.2,7.55,1.1499,0.0,23,1,100.0,1
424,2008-01-08 21:18:00,24.8,24.8,24.8,43.0,11.4,0.0,NaN,0.0,0.0,...,39.0,12.7,27.2,7.41,1.1500,0.0,23,1,100.0,1
425,2008-01-08 21:19:00,24.8,24.8,24.8,42.0,11.0,0.0,NaN,0.0,0.0,...,39.0,12.9,27.4,7.40,1.1489,0.0,24,1,100.0,1
426,2008-01-08 21:20:00,24.8,24.8,24.8,43.0,11.4,0.0,NaN,0.0,0.0,...,38.0,12.6,27.5,7.25,1.1489,0.0,23,1,100.0,1
427,2008-01-08 21:21:00,24.8,24.8,24.8,43.0,11.4,0.0,NaN,0.0,0.0,...,38.0,12.7,27.6,7.25,1.1482,0.0,24,1,100.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645877,2026-05-18 07:30:00,-0.1,0.3,-0.1,58.0,-7.4,0.0,NaN,0.0,0.0,...,27.0,-3.6,13.2,5.85,1.2222,0.0,351,1,100.0,15
645878,2026-05-18 07:45:00,-0.3,-0.1,-0.3,58.0,-7.6,0.0,NaN,0.0,0.0,...,27.0,-3.7,13.1,5.85,1.2229,0.0,351,1,100.0,15
645880,2026-05-18 08:15:00,-0.1,-0.1,-0.2,61.0,-6.7,0.0,NaN,0.0,0.0,...,27.0,-3.9,12.9,5.85,1.2242,0.0,352,1,100.0,15
645884,2026-05-18 09:15:00,8.8,8.8,6.4,36.0,-5.5,0.0,NaN,0.0,0.0,...,28.0,-3.5,12.9,6.05,1.2251,0.0,352,1,100.0,15
645885,2026-05-18 09:30:00,10.1,10.1,8.8,33.0,-5.5,0.0,NaN,0.0,0.0,...,28.0,-3.5,12.9,6.05,1.2251,0.0,351,1,100.0,15

## Removing unreliable data
According to the Weatherlink program documents, `ISS Recept` represents the overall quality level of the radio reception between the Vantage Pro consoles and the ISS transmitter. Reported as a number (percentage), the closer to `100`, the more reliable the data reported during the interval is; on the other hand, the closer to `0`, the more unreliable the data reported is.

In [10]:
display(pd.DataFrame(df["iss_recept"].value_counts().sort_index(ascending=False)).head(10))
print(f"Total rows: {len(df)}")

             count
iss_recept
100.0       638782
99.7           135
99.4           119
99.1           113
98.8            99
98.5            94
98.2            70
98.0            65
97.7            69
97.4            65

Total rows: 645927

Almost 99% of rows report an `ISS Recept` of 99% or greater. We will work with those records.

In [11]:
df_copy = df.copy()

In [12]:
df_copy = df_copy[df_copy["iss_recept"] >= 99]
df_copy

,record_date,avg_temp,hi_temp,low_temp,out_hum,dew_pt,wind_speed,wind_direction,wind_run,hi_speed,...,in_hum,in_dew,in_heat,in_emc,in_air_density,et,wind_samp,wind_tx,iss_recept,arc_int
1,2008-01-08 14:15:00,32.8,32.8,32.7,24.0,9.6,4.8,S,0.08,8.0,...,41.0,13.9,28.0,7.69,1.1484,0.00,24,1,100.0,1
2,2008-01-08 14:16:00,32.8,32.8,32.8,23.0,9.0,8.0,ESE,0.13,12.9,...,40.0,13.6,28.0,7.55,1.1482,0.00,23,1,100.0,1
3,2008-01-08 14:17:00,32.8,32.8,32.8,23.0,9.0,3.2,ESE,0.05,8.0,...,40.0,13.6,28.0,7.55,1.1482,0.00,23,1,100.0,1
4,2008-01-08 14:18:00,32.8,32.8,32.8,23.0,8.9,1.6,NE,0.03,3.2,...,40.0,13.6,28.0,7.55,1.1482,0.00,24,1,100.0,1
5,2008-01-08 14:19:00,32.8,32.8,32.8,22.0,8.3,1.6,ESE,0.03,8.0,...,40.0,13.6,28.0,7.55,1.1482,0.00,23,1,100.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645922,2026-05-18 18:45:00,15.6,16.7,15.6,18.0,-8.7,1.6,SSW,0.40,6.4,...,28.0,-0.7,16.0,5.96,1.2076,0.00,352,1,100.0,15
645923,2026-05-18 19:00:00,14.8,15.6,14.8,19.0,-8.6,1.6,SW,0.40,4.8,...,28.0,-0.7,15.9,5.96,1.2079,0.05,348,1,100.0,15
645924,2026-05-18 19:15:00,13.9,14.8,13.9,20.0,-8.7,0.0,SW,0.00,1.6,...,27.0,-1.3,15.7,5.85,1.2090,0.00,351,1,100.0,15
645925,2026-05-18 19:30:00,13.1,13.9,13.1,20.0,-9.4,0.0,SW,0.00,1.6,...,27.0,-1.4,15.6,5.85,1.2097,0.00,351,1,100.0,15
645926,2026-05-18 19:45:00,12.6,13.1,12.6,21.0,-9.2,1.6,SW,0.40,4.8,...,27.0,-1.6,15.4,5.85,1.2106,0.00,352,1,100.0,15

Checking the nulls again:

In [13]:
for column in df_copy:
    if df_copy[column].isnull().sum()/df_copy[column].notnull().sum() != 0:  
        print(f"{column}: {df_copy[column].isnull().sum()/df_copy[column].notnull().sum():.5f} ({df_copy[column].isnull().sum()})")

print(f"\nTotal null amount: {df_copy.isnull().sum().sum()}")

wind_direction: 0.53343 (222338)
hi_dir: 0.53288 (222190)
thsw_index: 0.18159 (98228)
uv_index: 0.18961 (101873)
uv_dose: 0.18961 (101873)
hi_uv: 0.18961 (101875)

Total null amount: 848377

Almost all columns got cleaned of nulls with this step. Those remaining with nulls are Wind related, THSW index and UV related measurements.

## Cleaning Wind measurements
### Calm (No Wind)

In [14]:
no_wind_filter = (df_copy["wind_direction"].isna()) & (df_copy["wind_speed"] == 0) & (df_copy["wind_run"] == 0) & (df_copy["hi_speed"] == 0) & (df_copy["hi_dir"].isna())
df_copy[no_wind_filter][["record_date", "wind_speed", "wind_direction", "wind_run", "hi_speed", "hi_dir"]]

,record_date,wind_speed,wind_direction,wind_run,hi_speed,hi_dir
418,2008-01-08 21:12:00,0.0,NaN,0.0,0.0,NaN
424,2008-01-08 21:18:00,0.0,NaN,0.0,0.0,NaN
425,2008-01-08 21:19:00,0.0,NaN,0.0,0.0,NaN
426,2008-01-08 21:20:00,0.0,NaN,0.0,0.0,NaN
427,2008-01-08 21:21:00,0.0,NaN,0.0,0.0,NaN
...,...,...,...,...,...,...
645877,2026-05-18 07:30:00,0.0,NaN,0.0,0.0,NaN
645878,2026-05-18 07:45:00,0.0,NaN,0.0,0.0,NaN
645880,2026-05-18 08:15:00,0.0,NaN,0.0,0.0,NaN
645884,2026-05-18 09:15:00,0.0,NaN,0.0,0.0,NaN
645885,2026-05-18 09:30:00,0.0,NaN,0.0,0.0,NaN

In [15]:
df_copy[["wind_direction", "hi_dir"]] = df_copy[["wind_direction", "hi_dir"]].replace(np.nan, "Calm")
df_copy[no_wind_filter][["record_date", "wind_speed", "wind_direction", "wind_run", "hi_speed", "hi_dir"]]

,record_date,wind_speed,wind_direction,wind_run,hi_speed,hi_dir
418,2008-01-08 21:12:00,0.0,Calm,0.0,0.0,Calm
424,2008-01-08 21:18:00,0.0,Calm,0.0,0.0,Calm
425,2008-01-08 21:19:00,0.0,Calm,0.0,0.0,Calm
426,2008-01-08 21:20:00,0.0,Calm,0.0,0.0,Calm
427,2008-01-08 21:21:00,0.0,Calm,0.0,0.0,Calm
...,...,...,...,...,...,...
645877,2026-05-18 07:30:00,0.0,Calm,0.0,0.0,Calm
645878,2026-05-18 07:45:00,0.0,Calm,0.0,0.0,Calm
645880,2026-05-18 08:15:00,0.0,Calm,0.0,0.0,Calm
645884,2026-05-18 09:15:00,0.0,Calm,0.0,0.0,Calm
645885,2026-05-18 09:30:00,0.0,Calm,0.0,0.0,Calm

In [16]:
for column in df_copy:
    if df_copy[column].isnull().sum()/df_copy[column].notnull().sum() != 0:  
        print(f"{column}: {df_copy[column].isnull().sum()/df_copy[column].notnull().sum():.5f} ({df_copy[column].isnull().sum()})")

print(f"\nTotal null amount: {df_copy.isnull().sum().sum()}")

thsw_index: 0.18159 (98228)
uv_index: 0.18961 (101873)
uv_dose: 0.18961 (101873)
hi_uv: 0.18961 (101875)

Total null amount: 403849

## Dropping THSW Index and UV related measurements

**THSW Index:** Calculation of this index is unknown.

**UV:** Redundancy.

In [17]:
df_copy = df_copy.drop(columns=["thsw_index", "uv_index", "uv_dose", "hi_uv"])
df_copy

,record_date,avg_temp,hi_temp,low_temp,out_hum,dew_pt,wind_speed,wind_direction,wind_run,hi_speed,...,in_hum,in_dew,in_heat,in_emc,in_air_density,et,wind_samp,wind_tx,iss_recept,arc_int
1,2008-01-08 14:15:00,32.8,32.8,32.7,24.0,9.6,4.8,S,0.08,8.0,...,41.0,13.9,28.0,7.69,1.1484,0.00,24,1,100.0,1
2,2008-01-08 14:16:00,32.8,32.8,32.8,23.0,9.0,8.0,ESE,0.13,12.9,...,40.0,13.6,28.0,7.55,1.1482,0.00,23,1,100.0,1
3,2008-01-08 14:17:00,32.8,32.8,32.8,23.0,9.0,3.2,ESE,0.05,8.0,...,40.0,13.6,28.0,7.55,1.1482,0.00,23,1,100.0,1
4,2008-01-08 14:18:00,32.8,32.8,32.8,23.0,8.9,1.6,NE,0.03,3.2,...,40.0,13.6,28.0,7.55,1.1482,0.00,24,1,100.0,1
5,2008-01-08 14:19:00,32.8,32.8,32.8,22.0,8.3,1.6,ESE,0.03,8.0,...,40.0,13.6,28.0,7.55,1.1482,0.00,23,1,100.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
645922,2026-05-18 18:45:00,15.6,16.7,15.6,18.0,-8.7,1.6,SSW,0.40,6.4,...,28.0,-0.7,16.0,5.96,1.2076,0.00,352,1,100.0,15
645923,2026-05-18 19:00:00,14.8,15.6,14.8,19.0,-8.6,1.6,SW,0.40,4.8,...,28.0,-0.7,15.9,5.96,1.2079,0.05,348,1,100.0,15
645924,2026-05-18 19:15:00,13.9,14.8,13.9,20.0,-8.7,0.0,SW,0.00,1.6,...,27.0,-1.3,15.7,5.85,1.2090,0.00,351,1,100.0,15
645925,2026-05-18 19:30:00,13.1,13.9,13.1,20.0,-9.4,0.0,SW,0.00,1.6,...,27.0,-1.4,15.6,5.85,1.2097,0.00,351,1,100.0,15
645926,2026-05-18 19:45:00,12.6,13.1,12.6,21.0,-9.2,1.6,SW,0.40,4.8,...,27.0,-1.6,15.4,5.85,1.2106,0.00,352,1,100.0,15

In [18]:
print(f"Total null amount: {df_copy.isnull().sum().sum()}")

Total null amount: 0

## Archive Interval
We will also keep the same archive interval for the records.

In [19]:
df_copy = df_copy[df_copy["arc_int"] == 15].reset_index(drop=True)
df_copy

,record_date,avg_temp,hi_temp,low_temp,out_hum,dew_pt,wind_speed,wind_direction,wind_run,hi_speed,...,in_hum,in_dew,in_heat,in_emc,in_air_density,et,wind_samp,wind_tx,iss_recept,arc_int
0,2008-01-18 03:45:00,15.0,15.0,14.9,74.0,10.4,0.0,Calm,0.0,0.0,...,43.0,12.9,26.0,8.05,1.1588,0.00,351,1,100.0,15
1,2008-01-18 04:00:00,14.8,15.0,14.7,75.0,10.4,0.0,Calm,0.0,0.0,...,44.0,13.1,25.9,8.16,1.1588,0.03,352,1,100.0,15
2,2008-01-18 04:15:00,14.5,14.7,14.4,76.0,10.3,0.0,Calm,0.0,0.0,...,44.0,13.0,25.8,8.17,1.1597,0.00,351,1,100.0,15
3,2008-01-18 04:30:00,14.3,14.4,14.3,76.0,10.2,0.0,S,0.0,1.6,...,44.0,12.9,25.7,8.17,1.1602,0.00,351,1,100.0,15
4,2008-01-18 04:45:00,14.2,14.3,14.1,76.0,10.0,0.0,Calm,0.0,0.0,...,44.0,12.8,25.6,8.18,1.1609,0.00,351,1,100.0,15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
634330,2026-05-18 18:45:00,15.6,16.7,15.6,18.0,-8.7,1.6,SSW,0.4,6.4,...,28.0,-0.7,16.0,5.96,1.2076,0.00,352,1,100.0,15
634331,2026-05-18 19:00:00,14.8,15.6,14.8,19.0,-8.6,1.6,SW,0.4,4.8,...,28.0,-0.7,15.9,5.96,1.2079,0.05,348,1,100.0,15
634332,2026-05-18 19:15:00,13.9,14.8,13.9,20.0,-8.7,0.0,SW,0.0,1.6,...,27.0,-1.3,15.7,5.85,1.2090,0.00,351,1,100.0,15
634333,2026-05-18 19:30:00,13.1,13.9,13.1,20.0,-9.4,0.0,SW,0.0,1.6,...,27.0,-1.4,15.6,5.85,1.2097,0.00,351,1,100.0,15
634334,2026-05-18 19:45:00,12.6,13.1,12.6,21.0,-9.2,1.6,SW,0.4,4.8,...,27.0,-1.6,15.4,5.85,1.2106,0.00,352,1,100.0,15

In [20]:
df_copy.describe()

,avg_temp,hi_temp,low_temp,out_hum,dew_pt,wind_speed,wind_run,hi_speed,wind_chill,heat_index,...,in_hum,in_dew,in_heat,in_emc,in_air_density,et,wind_samp,wind_tx,iss_recept,arc_int
count,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,...,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.000000,634335.0
mean,15.500415,15.720826,15.280533,59.738950,6.325967,2.333845,0.583899,7.240058,15.457110,14.905101,...,43.608327,6.720779,18.781692,8.348586,1.195333,0.040798,350.673885,1.000211,99.999663,15.0
std,8.453158,8.487145,8.417264,21.720624,4.259290,4.129452,1.031910,9.345878,8.433405,8.113555,...,8.520505,3.416618,4.908084,1.444290,0.026118,0.128738,1.463927,0.015880,0.015194,0.0
min,-4.400000,-4.300000,-4.500000,1.000000,-31.600000,0.000000,0.000000,0.000000,-4.400000,-4.700000,...,16.000000,-11.600000,5.600000,3.780000,1.089800,0.000000,339.000000,1.000000,99.100000,15.0
25%,9.100000,9.300000,8.900000,41.000000,3.700000,0.000000,0.000000,0.000000,9.100000,8.900000,...,37.000000,4.300000,14.700000,7.290000,1.173500,0.000000,351.000000,1.000000,100.000000,15.0
50%,14.300000,14.600000,14.100000,61.000000,6.700000,0.000000,0.000000,3.200000,14.300000,13.600000,...,43.000000,6.700000,18.700000,8.150000,1.194800,0.000000,351.000000,1.000000,100.000000,15.0
75%,21.800000,22.100000,21.600000,79.000000,9.300000,3.200000,0.800000,11.300000,21.800000,20.800000,...,49.000000,9.200000,23.200000,9.250000,1.216300,0.000000,351.000000,1.000000,100.000000,15.0
max,39.700000,39.800000,39.500000,100.000000,17.900000,25.700000,6.440000,62.800000,39.700000,38.100000,...,78.000000,17.400000,31.200000,15.710000,1.271300,0.940000,586.000000,3.000000,100.000000,15.0

In [21]:
df_copy.to_csv("clean_dataset.csv", index=False)